# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish npm package

on:
  push:
    branches: [ master, v* ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_PUSH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
      - name: Configure git user
        run: |
          git config --global user.name '${{ secrets.CI_PUSH_USER }}'
          git config --global user.email '${{ secrets.CI_PUSH_USER }}@users.noreply.github.com'
      - run: npm ci
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
      - run: npm run build
      - run: npm version patch -m "Upgrade to %s [skip ci]"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: git push
      - run: git push --tags
  publish-docs:
    name: Publish documentation to myUploads
    runs-on: ubuntu-latest
    needs: publish-npm
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      - run: |
          npm run compile
          cd ./builds
          npx bestzip ../docs.zip * 
          curl -f -X POST -F 'zippedFile=@../docs.zip' https://uploads.myblueprint.org/@myblueprint/react-virtualized/${{ steps.extract_version.outputs.version }} --header "X-MBP-APIKey: ${{ secrets.UPLOAD_APIKEY }}"
